<a href="https://colab.research.google.com/github/anushi12/Python-Libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list = [1, 2, 3, 4, 5]

In [ ]:
array = np.array(my_list)

In [ ]:
array

array([1, 2, 3, 4, 5])

In [ ]:
type(array)

numpy.ndarray

In [ ]:
a = [1, 2, 3, 4]

In [ ]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [ ]:
b = np.matrix(my_list)

In [ ]:
b

matrix([[1, 2, 3, 4, 5]])

In [ ]:
c = a

shallow copy

In [ ]:
c[0] = 100

In [ ]:
c

[100, 2, 3, 4]

In [ ]:
a

[100, 2, 3, 4]

deep copy

In [ ]:
d = np.copy(a)

In [ ]:
a[2] = 700

In [ ]:
a

[100, 2, 700, 4]

In [ ]:
d

array([100,   2,   3,   4])

In [ ]:
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i, j: i*j, (3,3))    # 0. means its data type is float

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring("234 234", sep = ' ')  # it will separate the string to form an array based on the delimiter

array([234., 234.])

Data types in numpy

In [ ]:
my_list = [1, 2 ,3 ,4 , 5, 6]

In [ ]:
arr = np.array(my_list)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.ndim(arr)            # ndim tells the dimensionality of an array

1

In [ ]:
arr1 = [[1,2, 3], [4, 5, 6]]

In [ ]:
e = np.array(arr1)

In [ ]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.ndim(e)

2

In [ ]:
e.shape

(2, 3)

In [ ]:
e.dtype # tells the data type of array

dtype('int64')

In [ ]:
arr1 = np.array([(1.5, 2, 3), (4, 5, 6)])

In [ ]:
arr1          # changed every value to float

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
list(range(5))      # this is not an error, range takes only integer value

TypeError: 'list' object is not callable

range takes only integer value but in numpy the arange data type can take floating values as well

In [ ]:
np.arange(2.3, 5.5)

array([2.3, 3.3, 4.3, 5.3])

we can also pass the jump value

In [ ]:
np.arange(2.3, 5.5, 0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [ ]:
np.arange(2.3, 5.5, 0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [ ]:
np.linspace(1,5, 10) # linspace divides the line into given equal parts between two values

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros([3, 4, 2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
one = np.ones(5)

In [ ]:
one

array([1., 1., 1., 1., 1.])

In [ ]:
one + 5

array([6., 6., 6., 6., 6.])

In [ ]:
np.empty([3,4])     # creates an empty array

array([[3.96104854e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [ ]:
np.eye(4)  # identity matrices

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.logspace(2,5, 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [ ]:
arr = np.random.randn(3, 5)

In [ ]:
arr

array([[ 0.90800255, -0.47461752,  1.06350099,  1.09254281,  0.54334525],
       [ 0.44169644, -1.4452846 , -1.46074288,  0.68395102, -0.39829506],
       [ 1.09192234,  1.54897184,  0.73679149,  1.27808247,  1.63764715]])

In [ ]:
arr.reshape(5,3)

array([[ 0.90800255, -0.47461752,  1.06350099],
       [ 1.09254281,  0.54334525,  0.44169644],
       [-1.4452846 , -1.46074288,  0.68395102],
       [-0.39829506,  1.09192234,  1.54897184],
       [ 0.73679149,  1.27808247,  1.63764715]])

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(arr)

0         1         2         3         4
0  0.908003 -0.474618  1.063501  1.092543  0.543345
1  0.441696 -1.445285 -1.460743  0.683951 -0.398295
2  1.091922  1.548972  0.736791  1.278082  1.637647

randn and rand are different in the way that randn produces values where the mean will be 0 and standard deviation will be 1. Whereas, rand produces any random values

In [ ]:
np.random.rand(3,5)

array([[0.19026251, 0.50260268, 0.87012552, 0.93135454, 0.31877108],
       [0.59806739, 0.9504761 , 0.21506939, 0.82797676, 0.03472267],
       [0.78994637, 0.86246705, 0.32710242, 0.53560531, 0.91468558]])

In [ ]:
np.random.randint(50,110, [3,4])      # produces random value between 50-110

array([[ 81,  91,  58,  52],
       [108,  66,  92,  60],
       [ 77,  70,  83,  95]])